/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesAddRouteImport } from './routes/notes/add'
import { Route as NotesIdRouteImport } from './routes/notes/$id'
import { Route as NotesIdEditRouteImport } from './routes/notes/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesAddRoute = NotesAddRouteImport.update({
  id: '/notes/add',
  path: '/notes/add',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdEditRoute = NotesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => NotesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/notes/add': typeof NotesAddRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/notes/add': typeof NotesAddRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes/$id': typeof NotesIdRouteWithChildren
  '/notes/add': typeof NotesAddRoute
  '/notes/$id/edit': typeof NotesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes/$id' | '/notes/add' | '/notes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes/$id' | '/notes/add' | '/notes/$id/edit'
  id: '__root__' | '/' | '/notes/$id' | '/notes/add' | '/notes/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesIdRoute: typeof NotesIdRouteWithChildren
  NotesAddRoute: typeof NotesAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/add': {
      id: '/notes/add'
      path: '/notes/add'
      fullPath: '/notes/add'
      preLoaderRoute: typeof NotesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id/edit': {
      id: '/notes/$id/edit'
      path: '/edit'
      fullPath: '/notes/$id/edit'
      preLoaderRoute: typeof NotesIdEditRouteImport
      parentRoute: typeof NotesIdRoute
    }
  }
}

interface NotesIdRouteChildren {
  NotesIdEditRoute: typeof NotesIdEditRoute
}

const NotesIdRouteChildren: NotesIdRouteChildren = {
  NotesIdEditRoute: NotesIdEditRoute,
}

const NotesIdRouteWithChildren =
  NotesIdRoute._addFileChildren(NotesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesIdRoute: NotesIdRouteWithChildren,
  NotesAddRoute: NotesAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
